name: GitHub‑Profile‑3D‑Contrib

on:
  # 00:00 JST（15:00 UTC）に毎日実行
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      # 1) 完全 clone（rebase 用）
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # ← 必須！
          persist-credentials: true # ← push に GITHUB_TOKEN を使う

      # 2) 3D 草画像生成（最新安定版）
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ← デフォルトトークンで十分
          USERNAME:      ${{ github.repository_owner }}
          SETTING_JSON:  conf/github-profile-3d-contrib.json

      # 3) 競合を避けてコミット & プッシュ
      - name: Commit & Push
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com

          # 最新コミットを取り込み履歴を直列化
          git pull --rebase origin main

          # 差分が無いならスキップ
          if git diff --quiet; then
            echo "Nothing to commit — skip push."
            exit 0
          fi

          git add -A .
          git commit -m "chore: update 3D contrib chart (auto)"
          git push
